"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _
# .env
load_dotenv()
SECRET_KEY_DJ = os.getenv("SECRET_KEY_DJ", "")
DJANGO_SETTINGS_MODULE = os.getenv("DJANGO_SETTINGS_MODULE", "")

# APP
APP_PROTOCOL = os.getenv("APP_PROTOCOL", "")
APP_HOST = os.getenv("APP_HOST", "")
APP_HOST_REMOTE = os.getenv("APP_HOST_REMOTE", "")
APP_PORT = os.getenv("APP_PORT", "")
APP_TIME_ZONE = os.getenv("APP_TIME_ZONE", "")

# db production
POSTGRES_MULTIPLE_DATABASES = os.getenv("POSTGRES_MULTIPLE_DATABASES", "")
POSTGRES_USER = os.getenv("POSTGRES_USER", "")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "")

POSTGRES_PORT = os.getenv("POSTGRES_PORT", "")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "")
DB_ENGINE = os.getenv("DB_ENGINE", "")

# db development
DATABASE_ENGINE_LOCAL = os.getenv("DATABASE_ENGINE_LOCAL", "")
DATABASE_LOCAL = os.getenv("DATABASE_LOCAL", "")

# jwt
JWT_ACCESS_TOKEN_LIFETIME_MINUTES = os.getenv("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", 5)
JWT_REFRESH_TOKEN_LIFETIME_DAYS = os.getenv("JWT_REFRESH_TOKEN_LIFETIME_DAYS", 1)

#file extension
f_extension = "pdf, docx"


# wink age's category
AGE_RATING_CHOICES = [
    ("----", _("Не учьтено")),
    ("0+", _("Без возрастных ограничений")),
    ("6+", _("От 6 лет")),
    ("12+", _("От 12 лет")),
    ("16+", _("От 16 лет")),
    ("18+", _("Совершеннолетним")),
]
# who is author of comment
AUTHOR_OF_COMMET = [
    ("AI", _("Рекомендация после анализа")),
    ("User", _("Комментарий к файлу"))
]
# rating  scenario after parsing.
COMPLIANCE_LEVEL_RATING_CHOICES = [
    ("----", _("Не учьтено")),
    ("None", _("Соответствует")),
    ("mild", _("Незначительное нарушение")),
    ("moderate", _("Существенное нарушение")),
    ("severe", _("Грубое нарушение")),
]

# status of the file to be parsing
STATUS_FILE = [
    ("--------", _("Не учьтено")),
    ("processing", _("В процессе")),
    ("ready", _("Завершено")),
    ("error", _("Ошибка")),
]

# '''Cookie'''
SESSION_COOKIE_HTTPONLY = False  # CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True # change to the True - CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF_COOKIE_SAMESITE = 'Lax'  # or 'Strict'
SESSION_COOKIE_AGE = 86400

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = f"{SECRET_KEY_DJ}".strip()
if not SECRET_KEY:
    raise ValueError("SECRET_KEY must be set in environment variables")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    f"{APP_HOST_REMOTE}".strip(),
    "127.0.0.1",
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': f'{DB_ENGINE}'.strip(),
        'NAME': f'{POSTGRES_MULTIPLE_DATABASES}'.strip(),
        'USER': f'{POSTGRES_USER}'.strip(),
        'PASSWORD': f"{POSTGRES_PASSWORD}".strip(),
        'HOST': f'{POSTGRES_HOST}'.strip(),
        'PORT': f'{POSTGRES_PORT}'.strip(),
        "KEY_PREFIX": "drive_",  # it's my prefix for the keys
    }
}

# DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')
if DEBUG:
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_SSL_REDIRECT = False # http is False & https is True
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
    WHITENOISE_MAX_AGE = 0
    WHITENOISE_USE_FINDERS = False
    # DB
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR /  "wink_db.sqlite3",
    }
    ALLOWED_HOSTS.pop(0)

# APPLICATION DEFINITION
INSTALLED_APPS = [
    "daphne",
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.contrib.settings',
    'wagtail',
    'taggit',
    'modelcluster',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'adrf',
    'channels',
    "webpack_loader",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "wink",
]


MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "wink.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "project.asgi.application"





# PASSWORD VALIDATION
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# HASH passwords
# https://docs.djangoproject.com/en/4.2/topics/auth/passwords/
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.BCryptPasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    "django.contrib.auth.hashers.MD5PasswordHasher",
]

# INTERNATIONALIZATION
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = f"{APP_TIME_ZONE.strip()}"

USE_I18N = True

USE_TZ = True

DATE_FORMAT = 'd.m.Y'
DATETIME_FORMAT = 'd.m.Y H:i'
USE_L10N = False

# STATIC FILES (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,  "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR,  "collectstatic/")
STATIC_URL = 'static/'

# '''WHITENOISE'''
# for a static files in production
# https://whitenoise.readthedocs.io/en/stable/django.html
WHITENOISE_MAX_AGE = 31536000  # static cache by 1 year
WHITENOISE_USE_FINDERS = True
WAGTAILDOCS_EXTENSIONS = list(f_extension.split(", "))# ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Options for file's repository/source
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


DEFAULT_CHARSET = "utf-8"



# '''CORS'''
# False - this value is default and it's means what the server don't accept from other sources.
CORS_ORIGIN_ALLOW_ALL = True
# Here, we allow the URL list for publicated
CORS_ALLOWED_ORIGINS = [
    f"http://{APP_HOST_REMOTE.strip()}:8000",
    "http://127.0.0.1:8000",
]


# Allow the methods to the methods in HTTP
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_ALL_ORIGINS=True

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "Authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "Accept-Language",
    "Content-Language"
]

# """CSRF""
# https://github.com/adamchainz/django-cors-headers?tab=readme-ov-file#csrf-integration
# https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS
# This is list from private of URL
CSRF_COOKIE_AGE = 1800 # seconds This is the time live of token (in COOKIE)
CSRF_TRUSTED_ORIGINS = [
    f"http://{APP_HOST_REMOTE.strip()}:8000",
    "http://127.0.0.1:8000",
    ]
# """REST_FRAMEWORK SETTINGS AND JWT-tokens"""
# https://pypi.org/project/djangorestframework-simplejwt/4.3.0/
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/stateless_user_authentication.html
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # This for works with sessions
        'rest_framework.authentication.TokenAuthentication',   # Options for API
    ),
    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes = int(JWT_ACCESS_TOKEN_LIFETIME_MINUTES)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(JWT_REFRESH_TOKEN_LIFETIME_DAYS)),
    "SIGNING_KEY": SECRET_KEY,
}

#"""DEBUG TOOLBAR - SERVER DAPHNE"""
DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: True,
}

# '''WEBPACK_LOADER'''
WEBPACK_LOADER = {
    "DEFAULT": {
        "CACHE": not DEBUG,
        # 'BUNDLE_DIR_NAME': '..\\frontend\\src\\bundles',
        "BUNDLE_DIR_NAME": "static",
        "STATS_FILE": os.path.join(
            BASE_DIR, "bundles/webpack-stats.json"
        ),

        "POLL_INTERVAL": 0.1,
        "TIMEOUT": None,
        "TEST": {
            # "NAME": "test_cloud",
        },
        "IGNORE": [
            # '.+\.map$'
            r".+\.hot-update.js",
            r".+\.map",
        ],
        "LOADER_CLASS": "webpack_loader.loader.WebpackLoader",
    }
}

# '''lOGGING'''
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

# """SWAGGER"""
# https://drf-yasg.readthedocs.io/en/stable/security.html#security-definitions

SWAGGER_USE_COMPAT_RENDERERS = False
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'VALIDATOR_URL': None,
    'exclude_namespaces':[

    ]
}
SPECTACULAR_SETTINGS = {
    'TITLE': 'API - Financial flow',
    'DESCRIPTION': 'Financial project - description',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# '''WAGTAIL'''
WAGTAIL_SITE_NAME = 'WINK_CINEMA'
# Replace the search backend
WAGTAILSEARCH_BACKENDS = {
 'default': {
   'BACKEND': 'wagtail.search.backends.elasticsearch8',
   'INDEX': 'myapp'
 }
}
WAGTAILADMIN_BASE_URL = CORS_ALLOWED_ORIGINS[0]

#
# # '''SSE'''
# SSE_ENCODE_BASE64 = True
