# Generated by Django 4.2.20 on 2025-11-07 03:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasisViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violations",
                    models.CharField(
                        db_column="violations",
                        help_text="Violations - the views of violations",
                        max_length=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z- ,]+$"
                            ),
                        ],
                        verbose_name="Violations",
                    ),
                ),
                (
                    "violations_comment",
                    models.CharField(
                        db_column="violations_comment",
                        help_text="Example - Нецензурная лексика - Мат, обсценная речь 16+ / 18+",
                        max_length=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z- +/0-9]+$"
                            ),
                        ],
                        verbose_name="Violations_comments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basis Violation",
                "verbose_name_plural": "Basis Violations",
                "db_table": "wink_violations",
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("0+", "Без возрастных ограничений"),
                            ("6+", "От 6 лет"),
                            ("12+", "От 12 лет"),
                            ("16+", "От 16 лет"),
                            ("18+", "Совершеннолетним"),
                        ],
                        db_column="target_audience",
                        default=("6+", "От 6 лет"),
                        help_text="Target audience of your document",
                        max_length=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Target Audience",
                    ),
                ),
                (
                    "reference_file",
                    models.CharField(
                        blank=True,
                        db_column="reference_file",
                        help_text="Reference File - it's the pathname of file inside the server",
                        max_length=100,
                        null=True,
                        verbose_name="Reference File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comments",
                "verbose_name_plural": "Comments",
                "db_table": "wink_comments",
            },
        ),
        migrations.CreateModel(
            name="FilesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FileField(
                        blank=True,
                        help_text="Upload the file - pdf, docx",
                        null=True,
                        upload_to="upload/%Y/%m/%d/",
                        verbose_name="File",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "size",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "db_table": "wink_files",
            },
        ),
        migrations.CreateModel(
            name="IntermediateViolationsComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violations_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Violations Quantity"
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("None", "Соответствует"),
                            ("mild", "Незначительное нарушение"),
                            ("moderate", "Существенное нарушение"),
                            ("severe", "Грубое нарушение"),
                        ],
                        default=("None", "Соответствует"),
                        help_text="Rating from violations",
                        max_length=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "refer",
                    models.CharField(
                        db_column="refer",
                        editable=False,
                        help_text="Reference link to the file - pdf, docx",
                        max_length=50,
                        unique=True,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "comments_user",
                    models.ForeignKey(
                        db_column="comments_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_violations",
                        to="wink.comments",
                        verbose_name="Comments of user",
                    ),
                ),
                (
                    "violations",
                    models.ForeignKey(
                        db_column="violations",
                        help_text="Violations - the views of violations",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_violations",
                        to="wink.basisviolation",
                        verbose_name="Violations",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntermediateFilesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violations_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Violations Quantity"
                    ),
                ),
                (
                    "refer",
                    models.UUIDField(
                        db_column="refer",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Reference link to the file - pdf, docx",
                        unique=True,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        db_column="file_id",
                        help_text="Select existing the file id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loaded_files",
                        to="wink.filesmodel",
                        verbose_name="File",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        help_text="Select the user id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "violations",
                    models.ManyToManyField(
                        blank=True,
                        db_column="violations",
                        help_text="Violations - the views of violations",
                        to="wink.basisviolation",
                        verbose_name="Violations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intermediate_files",
                "verbose_name_plural": "Intermediate_files",
                "db_table": "wink_intermediate_files",
            },
        ),
        migrations.AddField(
            model_name="comments",
            name="refer",
            field=models.OneToOneField(
                db_column="refer_file_uuid_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refers",
                to="wink.intermediatefilesmodel",
                to_field="refer",
                verbose_name="Reference File",
            ),
        ),
    ]
