# Generated by Django 4.2.20 on 2025-11-13 09:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasisViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violations",
                    models.CharField(
                        db_column="violations",
                        help_text="Violations - the views of violations",
                        max_length=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z- ,]+$"
                            ),
                        ],
                        verbose_name="Violations",
                    ),
                ),
                (
                    "violations_comment",
                    models.CharField(
                        db_column="violations_comment",
                        help_text="Example - Нецензурная лексика - Мат и другая 16+ / 18+",
                        max_length=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z- \\+/0-9]+$"
                            ),
                        ],
                        verbose_name="Violations_comments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basis Violation",
                "verbose_name_plural": "Basis Violations",
                "db_table": "wink_violations",
                "ordering": ["violations"],
            },
        ),
        migrations.CreateModel(
            name="CommentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comments"),
                ),
                (
                    "comment_author",
                    models.CharField(
                        choices=[
                            ("AI", "Рекомендация после анализа"),
                            ("User", "Комментарий к файлу"),
                        ],
                        default="User",
                        help_text="Comment author is AI  or User.",
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.RegexValidator(
                                regex="(^[A-Z][A-Za-z-_]+$)"
                            ),
                        ],
                        verbose_name="Comment author",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        db_column="created_at",
                        default="2025-11-13",
                        help_text="Created at",
                        null=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True,
                        db_column="updated_at",
                        help_text="Past time when the file was updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comments",
                "verbose_name_plural": "Comments",
                "db_table": "wink_comments",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FilesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FileField(
                        blank=True,
                        help_text="Upload the file - pdf, docx, json",
                        null=True,
                        upload_to="upload/%Y/%m/%d/",
                        verbose_name="File",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "size",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "db_table": "wink_files",
            },
        ),
        migrations.CreateModel(
            name="IntermediateFilesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violations_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Violations Quantity"
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("----", "Не учьтено"),
                            ("0+", "Без возрастных ограничений"),
                            ("6+", "От 6 лет"),
                            ("12+", "От 12 лет"),
                            ("16+", "От 16 лет"),
                            ("18+", "Совершеннолетним"),
                        ],
                        db_column="target_audience",
                        default="----",
                        help_text="Target audience for the film script",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.RegexValidator(regex="(^\\d+\\+$)"),
                        ],
                        verbose_name="Target Audience",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        db_column="created_at",
                        default="2025-11-13",
                        help_text="Created at",
                        null=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True,
                        db_column="updated_at",
                        help_text="Past time when the file was updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "refer",
                    models.UUIDField(
                        db_column="refer",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Reference link to the file - pdf, docx",
                        unique=True,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "status_file",
                    models.CharField(
                        choices=[
                            ("--------", "Не учьтено"),
                            ("processing", "В процессе"),
                            ("ready", "Завершено"),
                            ("error", "Ошибка"),
                        ],
                        db_column="status_file",
                        default="--------",
                        help_text="Status of the file to be parsing",
                        verbose_name="Status",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        db_column="file_id",
                        help_text="Select existing the file's id of user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loaded_files",
                        to="wink.filesmodel",
                        verbose_name="File",
                    ),
                ),
                (
                    "upload_ai",
                    models.OneToOneField(
                        blank=True,
                        db_column="file_ai",
                        help_text="Select existing the file id - This is the result of the analysis",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_files",
                        to="wink.filesmodel",
                        verbose_name="File",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        help_text="Select the user id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "violations",
                    models.ManyToManyField(
                        blank=True,
                        db_column="violations",
                        help_text="Violations - the views of violations",
                        to="wink.basisviolation",
                        verbose_name="Violations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Response AI",
                "verbose_name_plural": "Response AI",
                "db_table": "wink_intermediate_files",
            },
        ),
        migrations.CreateModel(
            name="IntermediateCommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violations_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Violations Quantity"
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("----", "Не учьтено"),
                            ("None", "Соответствует"),
                            ("mild", "Незначительное нарушение"),
                            ("moderate", "Существенное нарушение"),
                            ("severe", "Грубое нарушение"),
                        ],
                        default="----",
                        help_text="Rating from violations",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        db_column="created_at",
                        default="2025-11-13",
                        help_text="Created at",
                        null=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True,
                        db_column="updated_at",
                        help_text="Past time when the file was updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "comments_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="comments_user",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_user",
                        to="wink.commentsmodel",
                        verbose_name="Comments of user",
                    ),
                ),
                (
                    "refer",
                    models.OneToOneField(
                        db_column="refer",
                        help_text="Reference link to the file - pdf, docx",
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_inter",
                        to="wink.intermediatefilesmodel",
                        to_field="refer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Response AI",
                "verbose_name_plural": "Response AI",
            },
        ),
        migrations.AddField(
            model_name="commentsmodel",
            name="refer_file",
            field=models.OneToOneField(
                db_column="refer_file",
                help_text="Reference link to the file - pdf, docx",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refer_files",
                to="wink.intermediatefilesmodel",
                to_field="refer",
                verbose_name="Reference File",
            ),
        ),
    ]
