# Generated by Django 4.2.20 on 2025-11-03 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FilesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FileField(
                        db_column="file",
                        help_text="Upload the file - pdf, docx",
                        unique=True,
                        upload_to="uploads/files/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "docx"]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "db_table": "files",
                "unique_together": {("upload",)},
            },
        ),
        migrations.CreateModel(
            name="IntermediateFilesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refer",
                    models.UUIDField(
                        db_column="refer",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Reference link to the file - pdf, docx",
                        unique=True,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        db_column="file_id",
                        help_text="Select existing the file id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loaded_files",
                        to="wink.filesmodel",
                        verbose_name="File",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        help_text="Select the user id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intermediate_files",
                "verbose_name_plural": "Intermediate_files",
                "db_table": "intermediate_files",
                "unique_together": {("upload",)},
            },
        ),
    ]
