# Generated by Django 4.2.20 on 2025-11-10 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediatefilesmodel",
            name="target_audience",
            field=models.CharField(
                default="0+",
                help_text="Age of target audience - '0+' or '6+'",
                max_length=3,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxLengthValidator(3),
                    django.core.validators.RegexValidator(regex="(^\\d+\\+$)"),
                ],
                verbose_name="Audience",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("----", "Не учьтено"),
                    ("0+", "Без возрастных ограничений"),
                    ("6+", "От 6 лет"),
                    ("12+", "От 12 лет"),
                    ("16+", "От 16 лет"),
                    ("18+", "Совершеннолетним"),
                ],
                db_column="target_audience",
                default=("0+", "Без возрастных ограничений"),
                help_text="Target audience of your document",
                max_length=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Target Audience",
            ),
        ),
        migrations.AlterField(
            model_name="intermediateviolationscomment",
            name="rating",
            field=models.CharField(
                choices=[
                    ("----", "Не учьтено"),
                    ("None", "Соответствует"),
                    ("mild", "Незначительное нарушение"),
                    ("moderate", "Существенное нарушение"),
                    ("severe", "Грубое нарушение"),
                ],
                default=("----", "Не учьтено"),
                help_text="Rating from violations",
                max_length=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
