# Generated by Django 4.2.20 on 2025-11-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesmodel",
            name="upload",
            field=models.FileField(
                db_column="file",
                help_text="Upload the file - pdf, docx",
                upload_to="uploads/files/%Y/%m/%d/",
                verbose_name="File",
            ),
        ),
    ]
