# Generated by Django 4.2.20 on 2025-11-10 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0002_intermediatefilesmodel_target_audience_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="reference_file",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="target_audience",
        ),
        migrations.RemoveField(
            model_name="intermediateviolationscomment",
            name="violations",
        ),
        migrations.AddField(
            model_name="comments",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="intermediatefilesmodel",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("----", "Не учьтено"),
                    ("0+", "Без возрастных ограничений"),
                    ("6+", "От 6 лет"),
                    ("12+", "От 12 лет"),
                    ("16+", "От 16 лет"),
                    ("18+", "Совершеннолетним"),
                ],
                db_column="target_audience",
                default=("0+", "Без возрастных ограничений"),
                help_text="Target audience for the film script",
                max_length=5,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.RegexValidator(regex="(^\\d+\\+$)"),
                ],
                verbose_name="Target Audience",
            ),
        ),
    ]
