# Generated by Django 4.2.20 on 2025-11-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0002_alter_filesmodel_upload"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="filesmodel",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="intermediatefilesmodel",
            unique_together=set(),
        ),
    ]
