# Generated by Django 4.2.20 on 2025-11-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0003_alter_filesmodel_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesmodel",
            name="upload",
            field=models.FileField(
                db_column="file",
                help_text="Upload the file - pdf, docx",
                upload_to="files/%Y/%m/%d/",
                verbose_name="File",
            ),
        ),
    ]
