# Generated by Django 4.2.20 on 2025-11-10 04:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0003_remove_comments_reference_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={
                "ordering": ["id"],
                "verbose_name": "Comments",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="intermediateviolationscomment",
            options={
                "verbose_name": "Comment is intermediate",
                "verbose_name_plural": "Comments is intermediates",
            },
        ),
        migrations.AddField(
            model_name="comments",
            name="comment_author",
            field=models.CharField(
                choices=[
                    ("AI", "Рекомендация после анализа"),
                    ("User", "Комментарий к файлу"),
                ],
                default=("User", "Комментарий к файлу"),
                help_text="Comment author is AI  or User.",
                max_length=30,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(30),
                    django.core.validators.RegexValidator(regex="(^[A-Z][A-Za-z-_]+$)"),
                ],
                verbose_name="Comment author",
            ),
        ),
        migrations.AddField(
            model_name="intermediateviolationscomment",
            name="comments_ai",
            field=models.ForeignKey(
                db_column="comments_ai",
                default=None,
                help_text="Recommendation comment of AI",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_ai",
                to="wink.comments",
                verbose_name="Comments of user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="intermediateviolationscomment",
            name="comments_user",
            field=models.ForeignKey(
                blank=True,
                db_column="comments_user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_user",
                to="wink.comments",
                verbose_name="Comments of user",
            ),
        ),
        migrations.AlterField(
            model_name="intermediateviolationscomment",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("----", "Не учьтено"),
                    ("None", "Соответствует"),
                    ("mild", "Незначительное нарушение"),
                    ("moderate", "Существенное нарушение"),
                    ("severe", "Грубое нарушение"),
                ],
                default=("----", "Не учьтено"),
                help_text="Rating from violations",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
