# Generated by Django 4.2.20 on 2025-11-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0004_alter_filesmodel_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesmodel",
            name="upload",
            field=models.FileField(
                help_text="Upload the file - pdf, docx",
                upload_to="files/%Y/%m/%d/",
                verbose_name="File",
            ),
        ),
    ]
