# Generated by Django 4.2.20 on 2025-11-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0004_alter_comments_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="CommentsModel",
        ),
        migrations.RenameModel(
            old_name="IntermediateViolationsComment",
            new_name="IntermediateCommentModel",
        ),
    ]
