# Generated by Django 4.2.20 on 2025-11-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0005_alter_filesmodel_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesmodel",
            name="name",
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filesmodel",
            name="size",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="filesmodel",
            name="upload",
            field=models.FileField(
                help_text="Upload the file - pdf, docx",
                upload_to="upload/%Y/%m/%d/",
                verbose_name="File",
            ),
        ),
    ]
