# Generated by Django 4.2.20 on 2025-11-11 03:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0005_rename_comments_commentsmodel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basisviolation",
            options={
                "ordering": ["violations"],
                "verbose_name": "Basis Violation",
                "verbose_name_plural": "Basis Violations",
            },
        ),
        migrations.RemoveField(
            model_name="intermediatefilesmodel",
            name="violations",
        ),
        migrations.AddField(
            model_name="intermediatefilesmodel",
            name="created_at",
            field=models.DateField(
                blank=True,
                db_column="created_at",
                default=datetime.datetime.now,
                help_text="Created at",
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="basisviolation",
            name="violations_comment",
            field=models.CharField(
                db_column="violations_comment",
                help_text="Example - Нецензурная лексика - Мат и другая 16+ / 18+",
                max_length=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.RegexValidator(regex="^[A-Za-z- \\+/0-9]+$"),
                ],
                verbose_name="Violations_comments",
            ),
        ),
    ]
