# Generated by Django 4.2.20 on 2025-11-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0006_filesmodel_name_filesmodel_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesmodel",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="filesmodel",
            name="size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filesmodel",
            name="upload",
            field=models.FileField(
                blank=True,
                help_text="Upload the file - pdf, docx",
                null=True,
                upload_to="upload/%Y/%m/%d/",
                verbose_name="File",
            ),
        ),
    ]
