# Generated by Django 4.2.20 on 2025-11-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0006_alter_basisviolation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentsmodel",
            name="updated_at",
            field=models.DateField(
                auto_now=True,
                db_column="updated_at",
                help_text="Past time when the file was updated",
                verbose_name="Updated at",
            ),
        ),
        migrations.AddField(
            model_name="commentsmodel",
            name="upload",
            field=models.FileField(
                blank=True,
                db_column="upload",
                help_text="Upload file how result of parsing.",
                null=True,
                upload_to="",
                verbose_name="Upload file",
            ),
        ),
    ]
