# Generated by Django 4.2.20 on 2025-11-06 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0007_alter_filesmodel_name_alter_filesmodel_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasisViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violations",
                    models.CharField(
                        db_column="violations",
                        help_text="Violations - the views of violations",
                        max_length=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z- ,]+$"
                            ),
                        ],
                        verbose_name="Violations",
                    ),
                ),
                (
                    "violations_comment",
                    models.CharField(
                        db_column="violations_comment",
                        help_text="Example - Нецензурная лексика - Мат, обсценная речь 16+ / 18+",
                        max_length=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.RegexValidator(
                                regex="^[A-Za-z- +/0-9]+$"
                            ),
                        ],
                        verbose_name="Violations_comments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basis Violation",
                "verbose_name_plural": "Basis Violations",
                "db_table": "wink_violations",
            },
        ),
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violations_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Violations Quantity"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="intermediatefilesmodel",
            name="id",
        ),
        migrations.AlterField(
            model_name="filesmodel",
            name="size",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterModelTable(
            name="filesmodel",
            table="wink_files",
        ),
        migrations.AlterModelTable(
            name="intermediatefilesmodel",
            table="wink_intermediate_files",
        ),
        migrations.AddField(
            model_name="intermediatefilesmodel",
            name="quantity_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="wink.quantity",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="intermediatefilesmodel",
            name="violations",
            field=models.ManyToManyField(
                blank=True,
                db_column="violations",
                help_text="Violations - the views of violations",
                to="wink.basisviolation",
                verbose_name="Violations",
            ),
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "quantity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wink.quantity",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("None", "Соответствует"),
                            ("mild", "Незначительное нарушение"),
                            ("moderate", "Существенное нарушение"),
                            ("severe", "Грубое нарушение"),
                        ],
                        db_column="rating",
                        default=("None", "Соответствует"),
                        help_text="Rating from violations",
                        max_length=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("0+", "Без возрастных ограничений"),
                            ("6+", "От 6 лет"),
                            ("12+", "От 12 лет"),
                            ("16+", "От 16 лет"),
                            ("18+", "Совершеннолетним"),
                        ],
                        db_column="target_audience",
                        default=("6+", "От 6 лет"),
                        help_text="Target audience of your document",
                        max_length=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Target Audience",
                    ),
                ),
                (
                    "reference_file",
                    models.CharField(
                        blank=True,
                        db_column="reference_file",
                        help_text="Reference File - it's the pathname of file inside the server",
                        max_length=100,
                        null=True,
                        verbose_name="Reference File",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_column="author",
                        help_text="Who is uploading the document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="wink.intermediatefilesmodel",
                        verbose_name="Author",
                    ),
                ),
                (
                    "refer_file",
                    models.OneToOneField(
                        db_column="refer_file_uuid_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refers",
                        to="wink.intermediatefilesmodel",
                        to_field="refer",
                        verbose_name="Reference File",
                    ),
                ),
                (
                    "violations",
                    models.ManyToManyField(
                        blank=True,
                        db_column="violations",
                        help_text="Violations - the views of violations",
                        to="wink.basisviolation",
                        verbose_name="Violations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comments",
                "verbose_name_plural": "Comments",
                "db_table": "wink_comments",
            },
            bases=("wink.quantity",),
        ),
    ]
