# Generated by Django 4.2.20 on 2025-11-11 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0007_commentsmodel_updated_at_commentsmodel_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentsmodel",
            name="created_at",
            field=models.DateField(
                blank=True,
                db_column="created_at",
                default=datetime.date.today().strftime("%Y-%m-%d"),
                help_text="Created at",
                null=True,
                verbose_name="Created at",
            ),
        ),
    ]
