# Generated by Django 4.2.20 on 2025-11-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0008_commentsmodel_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intermediatecommentmodel",
            name="comments_ai",
        ),
    ]
