# Generated by Django 4.2.20 on 2025-11-11 04:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0009_remove_intermediatecommentmodel_comments_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediatecommentmodel",
            name="created_at",
            field=models.DateField(
                blank=True,
                db_column="created_at",
                default=datetime.date.today().strftime("%Y-%m-%d"),
                help_text="Created at",
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="intermediatecommentmodel",
            name="updated_at",
            field=models.DateField(
                auto_now=True,
                db_column="updated_at",
                help_text="Past time when the file was updated",
                verbose_name="Updated at",
            ),
        ),
        migrations.AddField(
            model_name="intermediatefilesmodel",
            name="updated_at",
            field=models.DateField(
                auto_now=True,
                db_column="updated_at",
                help_text="Past time when the file was updated",
                verbose_name="Updated at",
            ),
        ),
        migrations.AddField(
            model_name="intermediatefilesmodel",
            name="upload_ai",
            field=models.OneToOneField(
                blank=True,
                db_column="file_ai",
                help_text="Select existing the file id - This is the result of the analysis",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_files",
                to="wink.filesmodel",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="filesmodel",
            name="upload",
            field=models.FileField(
                blank=True,
                help_text="Upload the file - pdf, docx, json",
                null=True,
                upload_to="upload/%Y/%m/%d/",
                verbose_name="File",
            ),
        ),
    ]
