# Generated by Django 4.2.20 on 2025-11-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0010_intermediatecommentmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediatefilesmodel",
            name="violations",
            field=models.ManyToManyField(
                blank=True,
                db_column="violations",
                help_text="Violations - the views of violations",
                to="wink.basisviolation",
                verbose_name="Violations",
            ),
        ),
    ]
