# Generated by Django 4.2.20 on 2025-11-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0011_intermediatefilesmodel_violations"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediatefilesmodel",
            name="status_file",
            field=models.CharField(
                choices=[
                    ("--------", "Не учьтено"),
                    ("processing", "В процессе"),
                    ("ready", "Завершено"),
                    ("error", "Ошибка"),
                ],
                db_column="status_file",
                default=("--------", "Не учьтено"),
                help_text="Status of the file to be parsing",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
