# Generated by Django 4.2.20 on 2025-11-13 05:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0012_intermediatefilesmodel_status_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intermediatefilesmodel",
            options={
                "verbose_name": "Intermediate files",
                "verbose_name_plural": "Intermediate files",
            },
        ),
        migrations.RemoveField(
            model_name="commentsmodel",
            name="upload",
        ),
        migrations.AlterField(
            model_name="commentsmodel",
            name="comment_author",
            field=models.CharField(
                choices=[
                    ("AI", "Рекомендация после анализа"),
                    ("User", "Комментарий к файлу"),
                ],
                default=("User", "Комментарий к файлу"),
                help_text="Comment author is AI  or User.",
                max_length=30,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(30),
                    django.core.validators.RegexValidator(regex="(^[A-Z][A-Za-z-_]+$)"),
                ],
                verbose_name="Comment author",
            ),
        ),
        migrations.AlterField(
            model_name="intermediatecommentmodel",
            name="refer",
            field=models.OneToOneField(
                db_column="refer",
                editable=False,
                help_text="Reference link to the file - pdf, docx",
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                to="wink.intermediatefilesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="intermediatefilesmodel",
            name="upload",
            field=models.ForeignKey(
                db_column="file_id",
                help_text="Select existing the file's id of user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loaded_files",
                to="wink.filesmodel",
                verbose_name="File",
            ),
        ),
    ]
