# Generated by Django 4.2.20 on 2025-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0013_alter_intermediatefilesmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intermediatecommentmodel",
            name="refer",
            field=models.UUIDField(
                db_column="refer",
                editable=False,
                help_text="Reference link to the file - pdf, docx",
                unique=True,
                verbose_name="IntermediateFilesModel",
            ),
        ),
    ]
