# Generated by Django 4.2.20 on 2025-11-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0014_alter_intermediatecommentmodel_refer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsmodel",
            name="refer",
            field=models.UUIDField(
                db_column="refer",
                editable=False,
                help_text="Reference link to the file - pdf, docx",
                verbose_name="IntermediateFilesModel",
            ),
        ),
    ]
