# Generated by Django 4.2.20 on 2025-11-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0015_alter_commentsmodel_refer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsmodel",
            name="refer",
            field=models.OneToOneField(
                db_column="refer",
                help_text="Reference link to the file - pdf, docx",
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                to="wink.intermediatefilesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="intermediatecommentmodel",
            name="comments_user",
            field=models.ForeignKey(
                blank=True,
                db_column="comments_user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_user",
                to="wink.commentsmodel",
                to_field="refer",
                verbose_name="Comments of user",
            ),
        ),
    ]
