# Generated by Django 4.2.20 on 2025-11-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0016_alter_commentsmodel_refer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intermediatecommentmodel",
            name="refer",
            field=models.UUIDField(
                help_text="Reference link to the file - pdf, docx",
                unique=True,
                verbose_name="IntermediateFilesModel",
            ),
        ),
    ]
