# Generated by Django 4.2.20 on 2025-11-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0017_alter_intermediatecommentmodel_refer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intermediatefilesmodel",
            options={
                "verbose_name": "Response AI",
                "verbose_name_plural": "Response AI",
            },
        ),
    ]
