# Generated by Django 4.2.20 on 2025-11-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wink", "0018_alter_intermediatefilesmodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intermediatecommentmodel",
            options={
                "verbose_name": "Response AI",
                "verbose_name_plural": "Response AI",
            },
        ),
    ]
